import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Header from '@/components/header'
import Wrapper from '@/components/wrapper'
import Link from 'next/link'
import { useEffect, useState } from 'react'
import { useRouter } from 'next/router'
import { API_ENDPOINT } from '../../../config'
import AddGoalModal from '@/components/add-goal-modal'
import AddCardModal from '@/components/add-card-modal'
import AddSubModal from '@/components/add-sub-moda'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const router = useRouter();
  const { id } = router.query;

  const [liveFakeEvents, setLiveFakeEvents] = useState<any>([]);
  const [addGoalModal, setAddGoalModal] = useState<boolean>(false);
  const [addCardModal, setAddCardModal] = useState<boolean>(false);
  const [addSubModal, setAddSubModal] = useState<boolean>(false);

  useEffect(()=>{
    if(id){
        // WARNING: For GET requests, body is set to null by browsers.

        var xhr = new XMLHttpRequest();
        xhr.withCredentials = false;

        xhr.addEventListener("readystatechange", function() {
        if(this.readyState === 4) {
            setLiveFakeEvents(JSON.parse(this.responseText));
        }
        });

        xhr.open("GET", API_ENDPOINT+"/live-events/fake-event-details/"+id);

        xhr.send();
    }

  }, [id]); 


  function formatUnixTimestamp(unixTimestamp: number): string {
    const date = new Date(unixTimestamp * 1000);
  
    const day = date.getDate().toString().padStart(2, '0');
    const month = (date.getMonth() + 1).toString().padStart(2, '0');
    const year = date.getFullYear().toString().padStart(4, '0');
    const hours = date.getHours().toString().padStart(2, '0');
    const minutes = date.getMinutes().toString().padStart(2, '0');
  
    return `${day}.${month}.${year} ${hours}:${minutes}`;
  }



  const handleStageTypeChange = (event_id: string, stage: string, stage_type: string) => {
    var data = JSON.stringify({
        "event_id": event_id,
        "stage": stage,
        "stage_type": stage_type
      });
      
      var xhr = new XMLHttpRequest();
      xhr.withCredentials = false;
      
      xhr.addEventListener("readystatechange", function() {
        if(this.readyState === 4) {
          console.log(this.responseText);
          router.reload()
        }
      });
      
      xhr.open("PUT", API_ENDPOINT+"/live-events/change-event-stage-type");
      xhr.setRequestHeader("Content-Type", "application/json");
      
      xhr.send(data);
  }

  const handleStageChange = (event_id: string, stage: string) => {
    var data = JSON.stringify({
        "event_id": event_id,
        "stage": stage
      });
      
      var xhr = new XMLHttpRequest();
      xhr.withCredentials = false;
      
      xhr.addEventListener("readystatechange", function() {
        if(this.readyState === 4) {
          console.log(this.responseText);
          router.reload()
        }
      });
      
      xhr.open("PUT", API_ENDPOINT+"/live-events/change-event-stage");
      xhr.setRequestHeader("Content-Type", "application/json");
      
      xhr.send(data);
  }

  const handleDeleteEvent = (e:any, event_id: string) => {
    e.preventDefault()

    var confirmation = window.confirm("Are you sure you want to delete this event?");

    if (confirmation) {
        var data = JSON.stringify({
            "event_id": event_id, 
        });
        
        var xhr = new XMLHttpRequest();
        xhr.withCredentials = false;
        
        xhr.addEventListener("readystatechange", function() {
            if(this.readyState === 4) {
            console.log(this.responseText);
            router.push("/countries")
            //   router.reload()
            }
        });
        
        xhr.open("DELETE", API_ENDPOINT+"/live-events/delete-event");
        xhr.setRequestHeader("Content-Type", "application/json");
        
        xhr.send(data);
        }
  }

  return (
    <>
      <Head>
        <title>ADMIN | LIVESCORELY</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Header />
      <Wrapper>  

        <div
            style={{
                marginTop:'30px'
            }}
        >
            <div style={{
                display:'flex',
                alignItems:'center'
            }}>
            <span 
                style={{
                    paddingRight:'20px'
                }}
            >Live Event Summary</span>
            {/* <Link href={`/add-event/${name}?id=${id}&country_name=${country_name}`}
                style={{
                    color:'blue'
                }}
            >
                Add event +
            </Link> */}
            </div>
            <div style={{
                marginTop:'20px',
                display:'flex',
                flexDirection:'column',
                marginBottom:'20px'
            }}>
                 
            </div>


            <div
                style={{
                    marginTop:'20px'
                }}
            > 
                    <>
                        <div
                            style={{
                                width:'100%',
                                // height:'40px',
                                marginBottom:'20px',
                                display:'flex'
                            }}
                        >   
                            <div
                                style={{
                                    display:'flex',
                                    flexDirection:'column',
                                    width:'80%',

                                }}
                            >
                                <div
                                    style={{
                                        padding:"10px",
                                        display:'flex',
                                        width:'100%',
                                        background:'#eee',
                                        borderRadius:'5px',
                                        height:'fit-content'

                                    }}
                                >
                                    <div
                                        style={{
                                            width:'15%',
                                            display:'flex',
                                            alignItems:'center',
                                            justifyContent:'center'
                                        }}
                                    >
                                        <span
                                            style={{
                                                fontSize:'14px'
                                            }}
                                        > 
                                            45'
                                        </span>
                                    </div>
                                    <div
                                        style={{
                                            width:'50%',
                                            display:'flex',
                                            flexDirection:'column'
                                        }}
                                    >
                                        <div
                                            style={{
                                                marginBottom:'5px'
                                            }}
                                        >
                                            
                                            <span
                                                style={{
                                                    fontSize:'14px'
                                                }}
                                            > 
                                                {liveFakeEvents?.event?.home_name}
                                            </span>
                                        </div>

                                        <div
                                            style={{
                                                marginBottom:'0px'
                                            }}
                                        >
                                            
                                            <span
                                                style={{
                                                    fontSize:'14px',
                                                }}
                                            > 
                                                {liveFakeEvents?.event?.away_name}
                                            </span>
                                        </div>
                                    </div>

                                    <div
                                        style={{
                                            width:'20%',
                                            display:'flex',
                                            flexDirection:'column',
                                            justifyContent:'flex-end',
                                            borderRight:'1px solid #dcdcdc'
                                        }}
                                    >
                                        <div
                                            style={{
                                                marginBottom:'5px',
                                                display:'flex',
                                                alignItems:'center'
                                            }}
                                        >
                                            <div
                                                style={{
                                                    width:'20%'
                                                }}
                                            >
                                                <span
                                                    style={{
                                                        fontSize:'14px',
                                                        color:'red'
                                                    }}
                                                > 
                                                    {liveFakeEvents?.event?.home_score_current ? liveFakeEvents?.event?.home_score_current : 0}
                                                </span>
                                            </div>
                                            <div
                                                style={{
                                                    width:'20%'
                                                }}
                                            >
                                                <span
                                                    style={{
                                                        fontSize:'14px',
                                                        color:"#777777"
                                                    }}
                                                > 
                                                    ({liveFakeEvents?.event?.home_score_part_1 ? liveFakeEvents?.event?.home_score_part_1 : 0})
                                                </span>
                                            </div>
                                            
                                        </div>

                                        <div
                                            style={{
                                                marginBottom:'5px',
                                                display:'flex',
                                                alignItems:'center'
                                            }}
                                        >
                                            <div
                                                style={{
                                                    width:'20%'
                                                }}
                                            >
                                                <span
                                                    style={{
                                                        fontSize:'14px',
                                                        color:'red'
                                                    }}
                                                > 
                                                    {liveFakeEvents?.event?.away_score_current ? liveFakeEvents?.event?.away_score_current : 0}
                                                </span>
                                            </div>
                                            <div
                                                style={{
                                                    width:'20%'
                                                }}
                                            >
                                                <span
                                                    style={{
                                                        fontSize:'14px',
                                                        color:"#777777"
                                                    }}
                                                > 
                                                    ({liveFakeEvents?.event?.away_score_part_1 ? liveFakeEvents?.event?.away_score_part_1 : 0})
                                                </span>
                                            </div>
                                            
                                        </div>
                                    </div>

                                    <div
                                        style={{
                                            display:'flex',
                                            alignItems:'center',
                                            justifyContent:'center',
                                            width:'20%',
                                            borderRight:'1px solid #dcdcdc'

                                        }}
                                    >
                                        <span
                                            style={{
                                                fontSize:'13px'
                                            }}
                                        >
                                            {formatUnixTimestamp(liveFakeEvents?.event?.start_time)}
                                        </span>
                                    </div>

                                    <div
                                        style={{
                                            display:'flex',
                                            alignItems:'center',
                                            justifyContent:'center',
                                            width:'30%'

                                        }}
                                    > 

                                        {/* <Link href={`/edit-event/${liveFakeEvents?.event?._id}`} style={{marginLeft:'30px'}}> */}
                                        <button
                                            onClick={(e)=>{
                                                handleDeleteEvent(e, liveFakeEvents?.event?._id);
                                            }}
                                            style={{
                                                background:'transparent',
                                                border:'none',
                                                cursor:'pointer'
                                            }}
                                        >
                                            <span
                                                style={{
                                                    fontSize:'13px',
                                                    color:'red',
                                                    textDecoration:'underline',
                                                    
                                                }}
                                            >
                                                DELETE
                                            </span>
                                        </button>
                                        {/* </Link> */}

                                    </div>
                                </div>

                                <div
                                    style={{
                                        marginTop:'10px'
                                    }}
                                >
                                    {liveFakeEvents?.summary?.map((summary:any)=>(<>
                                        <div
                                            style={{
                                                background:"#eee",
                                                width:'100%',
                                                height:'30px',
                                                borderRadius:"5px",
                                                display:'flex',
                                                alignItems:'center'
                                            }}
                                        >
                                            <div
                                                style={{
                                                    padding:'10px',
                                                    display:'flex',
                                                    alignItems:'center',
                                                    width:'100%'
                                                }}
                                            >
                                                <div
                                                    style={{
                                                        display:'flex',
                                                        flex:1
                                                    }}
                                                >
                                                    <span
                                                        style={{
                                                            fontSize:'14px'
                                                        }}
                                                    >
                                                        {summary.stage_name}
                                                    </span>
                                                </div>
                                                <div>
                                                    <span
                                                        style={{
                                                            fontSize:'14px'
                                                        }}
                                                    >
                                                        {summary.result_home + " - " + summary.result_away }
                                                    </span>
                                                </div>
                                            </div>
                                        </div>
                                    </>))}
                                </div>
                            </div>


                            <div
                                style={{
                                    display:'flex',
                                    width:'20%',
                                    flexDirection:'column',
                                    alignItems:'center',
                                    textAlign:'left'
                                }}
                            >
                                <span
                                    style={{
                                        marginBottom:'10px',
                                        fontSize:'15px'
                                    }}
                                >Manipulate event:</span>

                                <button
                                    style={{
                                        width:'150px',
                                        height:'40px',
                                        cursor:'pointer',
                                        background:'black',
                                        outline:'none',
                                        border:'none',
                                        borderRadius:'5px',
                                        // marginTop:'10px', 
                                        color:'white'
                                    }}
                                    onClick={()=>{handleStageTypeChange(liveFakeEvents?.event?._id, "FIRST_HALF", "LIVE")}}
                                >
                                    START 1ST HALF
                                </button>

                                <button
                                    style={{
                                        width:'150px',
                                        height:'40px',
                                        cursor:'pointer',
                                        background:'red',
                                        outline:'none',
                                        border:'none',
                                        borderRadius:'5px',
                                        marginTop:'10px', 
                                        color:'white'

                                    }}
                                    onClick={()=>{handleStageChange(liveFakeEvents?.event?._id, "HALF_TIME")}}
                                >
                                    SET HALF TIME
                                </button>

                                <button
                                    style={{
                                        width:'150px',
                                        height:'40px',
                                        cursor:'pointer',
                                        background:'#0055ff',
                                        outline:'none',
                                        border:'none',
                                        borderRadius:'5px',
                                        marginTop:'10px', 
                                        color:'white'

                                    }}
                                    onClick={()=>{handleStageChange(liveFakeEvents?.event?._id, "SECOND_HALF")}}
                                >
                                    START 2ND HALF
                                </button>

                                <button
                                    style={{
                                        width:'150px',
                                        height:'40px',
                                        cursor:'pointer',
                                        background:'green',
                                        outline:'none',
                                        border:'none',
                                        borderRadius:'5px',
                                        marginTop:'10px',
                                        color:'white'

                                    }}
                                    onClick={()=>{setAddGoalModal(true)}}
                                >
                                    ADD GOAL
                                </button>


                                <button
                                    style={{
                                        width:'150px',
                                        height:'40px',
                                        cursor:'pointer',
                                        background:'#9c27b0',
                                        outline:'none',
                                        border:'none',
                                        borderRadius:'5px',
                                        marginTop:'10px',
                                        color:'white'

                                    }}
                                    onClick={()=>{setAddCardModal(true)}}
                                >
                                    ADD CARD
                                </button>

                                <button
                                    style={{
                                        width:'150px',
                                        height:'40px',
                                        cursor:'pointer',
                                        background:'#795548',
                                        outline:'none',
                                        border:'none',
                                        borderRadius:'5px',
                                        marginTop:'10px',
                                        color:'white'
                                    }}
                                    onClick={()=>{setAddSubModal(true)}}
                                >
                                    MAKE SUB.
                                </button>

                                <button
                                    style={{
                                        width:'150px',
                                        height:'40px',
                                        cursor:'pointer',
                                        background:'#f44336',
                                        outline:'none',
                                        border:'none',
                                        borderRadius:'5px',
                                        marginTop:'10px',
                                        color:'white'
                                    }}
                                    onClick={()=>{handleStageTypeChange(liveFakeEvents?.event?._id, "FINISHED", "FINISHED")}}
                                >
                                    END MATCH
                                </button>

                                <button
                                    style={{
                                        width:'150px',
                                        height:'40px',
                                        cursor:'pointer',
                                        background:'#2196f3',
                                        outline:'none',
                                        border:'none',
                                        borderRadius:'5px',
                                        marginTop:'10px',
                                        color:'white'
                                    }}
                                    // onClick={()=>{handleStageChange(liveFakeEvents?.event?._id, "EXTRA_TIME")}}
                                >
                                    SET EXTRA TIME
                                </button>
                            </div>

                        </div>
                    </> 
            </div>
        </div>
      </Wrapper>

      {addGoalModal && 
        <AddGoalModal 
            liveFakeEvents={liveFakeEvents}
        />
      }
      {addCardModal && 
        <AddCardModal 
            liveFakeEvents={liveFakeEvents}
        />
      }
      {addSubModal && 
        <AddSubModal 
            liveFakeEvents={liveFakeEvents}
        />
      }
    </>
  )
}
