import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Header from '@/components/header'
import Wrapper from '@/components/wrapper'
import Link from 'next/link'
import { useEffect, useState } from 'react'
import { API_ENDPOINT } from '../../config'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [countires, setCountries] = useState<any>([]);
  useEffect(()=>{


    var xhr = new XMLHttpRequest();
    xhr.withCredentials = false;

    xhr.addEventListener("readystatechange", function() {
    if(this.readyState === 4) {
        setCountries(JSON.parse(this.responseText));
    }
    });

    xhr.open("GET", API_ENDPOINT+"/live-events/tournaments_stages");

    xhr.send();

  }, []);

  console.log(countires)

  return (
    <>
      <Head>
        <title>ADMIN | LIVESCORELY</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Header />
      <Wrapper>  

        <div
            style={{
                marginTop:'30px'
            }}
        >
            <div style={{
                display:'flex',
                alignItems:'center'
            }}>
            <span 
                style={{
                    paddingRight:'20px'
                }}
            >All countires</span>
            {/* <Link href="/add-country"
                style={{
                    color:'blue'
                }}
            >
                Add country +
            </Link> */}
            </div>
            <div style={{
                marginTop:'20px',
                display:'flex',
                flexDirection:'column',
                marginBottom:'20px'
            }}>
                {countires && countires?.tournaments_stages?.map((country: any)=> (
                    <>
                        <Link href={`/country/${country?.country_name}?id=${country?.country_id}`}
                        
                            style={{
                                color:'blue',
                                marginBottom:'10px'
                            }}
                        >
                            {country.country_name}
                        </Link>
                    </>
                ))}
            </div>

        </div>
      </Wrapper>
    </>
  )
}
