import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Header from '@/components/header'
import Wrapper from '@/components/wrapper'
import Link from 'next/link'
import { ChangeEvent, useEffect, useState } from 'react'
import { useRouter } from 'next/router'
import { API_ENDPOINT } from '../../../config'
import moment, { Moment } from "moment";

import DateTime from "react-datetime";
import "react-datetime/css/react-datetime.css";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const router = useRouter();
  const { league, id:country_id, country_name} = router.query;
 
  const [homeTeam, setHomeTeam] = useState('');
  const [awayTeam, setAwayTeam] = useState('');
  const [dateTime, setDateTime] = useState<number | null>(null);

  const homeTeamInput = (event: ChangeEvent<HTMLInputElement>) => {
    setHomeTeam(event.target.value);
  };
  
  const awayTeamInput = (event: ChangeEvent<HTMLInputElement>) => {
    setAwayTeam(event.target.value);
  };

  const handleAddLeague = () => {
    // WARNING: For POST requests, body is set to null by browsers.
        if(dateTime && homeTeam && awayTeam){ 
            var data = JSON.stringify({
                "league_name": league,
                "country_id": country_id,
                "country_name": country_name,
                "start_time": dateTime,
                "stage_start_time": dateTime,
                "home_name": homeTeam,
                "home_image": "",
                "away_name": awayTeam,
                "away_image": ""
            });
            
            var xhr = new XMLHttpRequest();
            xhr.withCredentials = false;
            
            xhr.addEventListener("readystatechange", function() {
                if(this.readyState === 4) {
                    router.push(`/league/${league}?id=${country_id}?country_name=${country_name}`)
                }
            });
            
            xhr.open("POST", API_ENDPOINT+"/live-events/add-live-event");
            xhr.setRequestHeader("Content-Type", "application/json");
            
            xhr.send(data);
        }
  }


  const handleDateTimeChange = (value: string | Moment) => {
    if (typeof value === "string") {
      const unixTimestamp = Math.floor(new Date(value).getTime() / 1000);
      setDateTime(unixTimestamp);
    } else if (moment.isMoment(value)) {
      const unixTimestamp = Math.floor(value.toDate().getTime() / 1000);
      setDateTime(unixTimestamp);
    } else {
      setDateTime(null);
    }
  };



//   const handleInputChange = (event: ChangeEvent<HTMLInputElement>) => {
//     // Handle input changes for league name
//   };


  return (
    <>
      <Head>
        <title>ADMIN | LIVESCORELY</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Header />
      <Wrapper>  

        <div
            style={{
                marginTop:'30px',
                display:'flex',
                flexDirection:'column',
                height:'100vh'
            }}
        >
            <div style={{
                display:'flex',
                flexDirection:'column'
            }}>
            <span 
                style={{
                    paddingRight:'20px'
                }}
            >Add new live event in: {country_name} - {league} <b><span 
                style={{
                    textTransform:'uppercase'
                }}
            >{}</span></b></span>
            {/* <Link href={`/add-league/${name}`}
                style={{
                    color:'blue'
                }}
            > 
            </Link> */}
            <div style={{
                marginTop:'20px',
                display:'flex',
                flexDirection:'column',
                width:'300px'
            }}>


                <div style={{
                    marginTop:"15px",
                    display:'flex',
                    flexDirection:'column'
                }}>
                    <span>Event start time:</span>
                    <DateTime
                        inputProps={{
                        placeholder: "Select date and time",
                        style: {
                            outline: "none",
                            width: "300px",
                            height: "35px",
                            backgroundColor: "white",
                            padding: 1,
                            border: "1px solid grey",
                            borderRadius: "5px",
                            paddingLeft: "5px",
                            paddingRight: "5px",
                            color: "black"
                        }
                        }}
                        value={dateTime ? moment.unix(dateTime) : undefined}
                        onChange={handleDateTimeChange}
                    />
                </div>

                <div style={{
                    marginTop:"15px",
                    display:'flex',
                    flexDirection:'column'
                }}>
                    <span>Home team name:</span>
                    <input
                        placeholder='Home team'
                        style={{
                            outline:'none',
                            width:'300px',
                            height:'35px',
                            backgroundColor:'white',
                            padding:1,
                            border:'1px solid grey',
                            borderRadius:'5px',
                            paddingLeft:'5px',
                            paddingRight:'5px',
                            color:'black'
                        }}
                        value={homeTeam}
                        onChange={homeTeamInput}
                    />
                </div>

                <div style={{
                    marginTop:"15px",
                    display:'flex',
                    flexDirection:'column'
                }}>
                    <span>Away team name:</span>
                    <input
                        placeholder='Home team'
                        style={{
                            outline:'none',
                            width:'300px',
                            height:'35px',
                            backgroundColor:'white',
                            padding:1,
                            border:'1px solid grey',
                            borderRadius:'5px',
                            paddingLeft:'5px',
                            paddingRight:'5px',
                            color:'black'
                        }}
                        value={awayTeam}
                        onChange={awayTeamInput}
                    />
                </div>
                <button
                    style={{
                        marginTop:'10px',
                        height:'30px',
                        borderRadius:'5px',
                        border:'none',
                        color:'white',
                        backgroundColor:'black',
                        cursor:'pointer'
                    }}
                    onClick={()=>{handleAddLeague()}}
                >
                    ADD
                </button>
            </div>
            </div>
             

        </div>
      </Wrapper>
    </>
  )
}
